// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://winpnzhnlduyxrcalmjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbnBuemhubGR1eXhyY2FsbWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MDkyMjgsImV4cCI6MjA1NDA4NTIyOH0.INcFZ9tUDj4O2XbthHIDqTsC4tLdz9_UhkXD4hdIdw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);